### ISSUE TITLE
Expansion not working in latest versions

### ISSUE THREAD

**Issue by neutvd** [EnvriPlus-PROV/EnvriProvTemplates#3]
Hi, the latest version gives the following backtrace when trying to expand the binding and template attached (in zip file):

```
python ./bin/expandTemplate.py --infile 1991.trig --bindings 
[provtemplates-issue.zip](https://github.com/EnvriPlus-PROV/EnvriProvTemplates/files/4117568/provtemplates-issue.zip)

bindings.json --bindver3 --outfile test-expand.provn
Traceback (most recent call last):
  File "./bin/expandTemplate.py", line 88, in <module>
    exp=provconv.instantiate_template(template, bindings_dict)
  File "/home/neutvd/anaconda3/envs/provtemplatecatalog/lib/python3.8/site-packages/EnvriProvTemplates-0.2.1-py3.8.egg/provtemplates/provconv.py", line 1252, in instantiate_template
  File "/home/neutvd/anaconda3/envs/provtemplatecatalog/lib/python3.8/site-packages/EnvriProvTemplates-0.2.1-py3.8.egg/provtemplates/provconv.py", line 903, in add_records
  File "/home/neutvd/anaconda3/envs/provtemplatecatalog/lib/python3.8/site-packages/EnvriProvTemplates-0.2.1-py3.8.egg/provtemplates/provconv.py", line 1190, in attr_match
IndexError: list index out of range
```

I had to fix a python3 issue in the expandTemplate.py script. See my merge request: https://github.com/EnvriPlus-PROV/EnvriProvTemplates/pull/2

I reverted back to commit 04b6ccca5c9c4e7b121a0c4567e6b628352f3a6f to make it work again. Can you also give us an update on the maintenance status of the project? Since EnvriPlus funding has ended as far as I (and @aspinuso) know. Will this project and https://github.com/EnvriPlus-PROV/ProvTemplateCatalog still be maintained?

Thank you.

**Comment by neutvd** [comment]
With commit 0720912b9880df8f474f5daa8104a73277a6a657 this issue seems fixed.

**Comment by d0rg0ld** [comment]
Just discovered a typo in a removed comment, fixed this in the most recent commit. please let me know if everrything works now. thanks!
